### ISSUE TITLE
Keep me in the loop

### ISSUE THREAD

**Issue by R4ZZ3** [aalto-speech/evaluation_of_speech_embedding_methods#1]
Hi,

Rasmus from Finnish-NLP here.
Nice that you include our model in your research (Finnish-NLP/wav2vec2-xlsr-300m-finnish-lm)
Please let us know once the research publications are out. Eagerly waiting.
I also generated DOI for the model repo for referencing:

@misc {finnish-nlp_2024,
	author       = { {Finnish-NLP} },
	title        = { wav2vec2-xlsr-300m-finnish-lm (Revision cadc726) },
	year         = 2024,
	url          = { https://huggingface.co/Finnish-NLP/wav2vec2-xlsr-300m-finnish-lm },
	doi          = { 10.57967/hf/2253 },
	publisher    = { Hugging Face }
}

**Comment by Tetrix** [comment]
Hi Rasmus,

The publication is now available as open access. Here is the DOI: https://doi.org/10.1109/TASLP.2024.3426301

**Comment by R4ZZ3** [comment]
Great job and really nice paper! 
From fast skimming I did not get which model was the wav2vec2-ft? Was it the one above or some other model version?

**Comment by R4ZZ3** [comment]
And actually one thing that came to my mind a while ago and this paper also gives some ideas is that I have not used any embedding based balancing on our ASR finetunes. 
These embedding methods combined with methods like "ClusterClipping" could maybe help in ASR finetunes to make the models more balanced on various ages, genders, dialects etch https://arxiv.org/pdf/2402.14526

**Comment by Tetrix** [comment]
Yes, the wav2vec2-ft is the one from above (Finnish-NLP/wav2vec2-xlsr-300m-finnish-lm). In the description of the repo I put all the models used in the study and a reference to them.

I haven't heard about "ClusterClipping" before, but from quick browsing through the paper it seems like a promising method for making the models more robust. I think some people in our group have done some study on curriculum learning which might also help with model robustness.
